# Generated by Django 4.2.7 on 2024-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_phone_number_customuser_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='branch',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
